global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

#  - job_name: 'node_exporter'
#    scrape_interval: 5s
#    static_configs:
#     - targets:  
#        - '192.168.144.134:9100'

  - job_name: 'cy-weather-api'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'cy-weather-api:8000'

