name: trivy tests

on:
  push:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.24.0

      - name: Clear cache
        run: trivy clean --all

      - name: Download DB
        run: trivy db download

      - name: Scan nginx image
        run: trivy image --severity HIGH,CRITICAL nginx:latest
